name: watchers_widget
description: Watchers Chat SDK
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  sizer: ^2.0.15
  formz: ^0.4.1
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.5
  socket_io_client: ^2.0.0
  freezed: ^2.1.0+1
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  get_it: ^7.2.0
  flutter_svg: ^1.1.3
  freezed_annotation: ^2.1.0
  bloc_concurrency: ^0.2.0
  badges: ^2.0.3
  dartz: ^0.10.1
  intl: ^0.17.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  logger: ^1.1.0
  uuid: ^3.0.6
  flutter_lints: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/emoji/