class Strings {
  Strings._();

  static String get termsAndConditions => '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut placerat enim, vel pharetra arcu. Pellentesque ut diam sed augue posuere congue. Vivamus congue a neque non vestibulum. Sed ac volutpat arcu. Nullam faucibus aliquet ipsum in interdum. Suspendisse finibus orci sit amet turpis maximus placerat. Fusce purus dui, lobortis et sagittis eget, condimentum dictum lacus. Proin feugiat eros non leo mollis, sit amet congue nibh sollicitudin. Aenean rhoncus euismod ligula. Nullam auctor cursus ligula quis iaculis. Morbi nec tincidunt ante, non convallis mauris. Suspendisse potenti. Aliquam gravida vestibulum massa dapibus dictum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur iaculis venenatis ornare. Etiam tincidunt ut risus a bibendum. Sed sagittis justo velit, nec efficitur libero sodales at. Vestibulum semper, libero sit amet fermentum pretium, tortor lorem ornare mi, a tincidunt ligula est ac justo. Curabitur id scelerisque sem. Aliquam erat volutpat. In interdum eros quam, a bibendum elit vehicula vitae. Integer congue ligula at sem euismod dapibus. Aliquam quam felis, pretium at ullamcorper in, sagittis ac nisl. Aenean feugiat sem sit amet odio egestas elementum. Praesent a libero in nibh tristique mattis. Sed tortor nibh, molestie non cursus eget, accumsan id sem. Donec mattis ex et massa eleifend fermentum.

Nullam pretium placerat sollicitudin. Integer eros sapien, pharetra eget vulputate sed, accumsan quis mauris. Etiam tincidunt massa a cursus ultricies. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque quis dictum leo. Donec elementum luctus purus. Curabitur sagittis vestibulum dui, et cursus lectus consequat facilisis. Integer a arcu a ex sagittis congue. Sed iaculis mi ac dui sodales condimentum. Mauris vitae ex leo. In euismod ipsum sed velit mattis, non vulputate dolor euismod. Phasellus quis ex nunc.''';

  static String get privacyPolicy => '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ac sodales elit. Vivamus et massa sit amet metus feugiat volutpat. Nam sed purus at risus mollis condimentum a vitae nibh. Donec volutpat ultrices pretium. Praesent odio eros, vestibulum et tortor at, mollis faucibus nisl. Quisque laoreet maximus nibh non consectetur. Cras ultrices vulputate tortor quis sollicitudin. In eu enim eros. Donec id porta elit.

Sed imperdiet felis a lectus euismod euismod. Fusce dignissim mi a arcu malesuada, vel suscipit quam vulputate. Suspendisse id est et neque volutpat bibendum. Suspendisse potenti. Pellentesque eget porta enim. Proin commodo placerat ante ac semper. Curabitur nec felis ut enim sagittis efficitur. Ut convallis ut enim eu condimentum. Pellentesque sed odio dui. Integer venenatis massa eget nunc luctus auctor.

Cras in gravida est. Pellentesque eget facilisis quam. Quisque gravida, est eget pharetra commodo, massa lacus ornare lacus, id facilisis metus purus vel metus. Etiam eget rhoncus nulla, id tincidunt velit. Mauris et lorem sit amet dui vehicula fermentum. Praesent non augue dui. Ut tempor ullamcorper felis at maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec eros dolor, mollis vel fringilla sit amet, pharetra vel felis. Donec nec pulvinar elit, id pretium erat. Nullam convallis dapibus turpis sed bibendum. Maecenas in viverra neque. Praesent bibendum pharetra quam, at gravida erat consectetur eget. Nulla id quam malesuada, fermentum augue eget, efficitur justo. Integer nec purus facilisis libero lacinia consectetur. Quisque vel finibus arcu. gggggg ggggg ggggggggggg gggggfgdfgdfg gfdgfdgdfgfdg''';
}
